alias src="cd ~/Program/src"
alias bin="cd ~/Program/bin"
alias doc="cd ~/Program/doc"
alias setclip="xclip -selection c"
alias getclip="xclip -selection c -o"
alias exec="chmod a+x"
alias vi="nvim"
alias setupbluetooth="pactl load-module module-bluetooth-discover"
alias tmux="TERM=screen-256color-bce tmux"
alias fixDNS='echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null'
alias la="ls -a"
alias mkbuild="cd build && make && cd .. && ./bin/main.py"
